### ISSUE TITLE
сканирование падает на call sp_mark_dbl(1)

### ISSUE THREAD

**Issue by jarmush** [mitshel/sopds#15]
sopds-scan.py падает при вызове процедуры sp_mark_dbl()

вывод в консоли
```
2016-11-06 12:55:42,621 INFO     Starting mark_double proc with DUBLICATES_FIND param = 1
Traceback (most recent call last):
  File "/opt/sopds/py/sopds-scan.py", line 40, in <module>
    scanner.scan_all()
  File "/opt/sopds/py/sopdscan.py", line 102, in scan_all
    self.opdsdb.mark_double(self.cfg.DUBLICATES_FIND)
  File "/opt/sopds/py/sopdsdb.py", line 893, in mark_double
    cursor.execute(sql,data)
  File "/usr/lib/python3.4/site-packages/mysql/connector/cursor.py", line 507, in execute
    self._handle_result(self._connection.cmd_query(stmt))
  File "/usr/lib/python3.4/site-packages/mysql/connector/connection.py", line 722, in cmd_query
    result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
  File "/usr/lib/python3.4/site-packages/mysql/connector/connection.py", line 640, in _handle_result
    raise errors.get_exception(packet)
mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'AUTHORS' at row 56
```

**Comment by mitshel** [comment]
Пока попробуйте отключить поиск дубликатов.

По данной проблеме напишите пожалуйста на форуме.
В основном SOPDS работает без ошибок, однако из за различных версий 
MYSQL, его настроек и других ньюансов, связанных с различием базовых ОС 
возникают различные неприятности.
Думаю Вам смогут помочь участники форума.

В настоящее время занимаюсь подготовкой новой, сильно переработанной 
версии, поэтому по  актуальной на данной момент версии 0.23.4 изменения 
вносится скорее всего уже не будут.

P.S.: проблема с дубликатми и ее решение уже где-то была ранее описана 
на формуме. Насколько я помню, указанная вами процедура очень 
требовательная к ресурсам и проблема появляется если в каталоге, которое 
MYSQL использует как временный не хватает места.

Удачи!


06.11.2016 13:17, Anatoly Gorodilov пишет:
