### ISSUE TITLE
Ошибка запуска после обновления- Fedora32

### ISSUE THREAD

**Issue by lalexs75** [mitshel/sopds#60]
Планово провёл обвление с Fedora31 на Fedora32
SOPDS перестал запускаться. 
Как я понял - отсутсвует модуль six в django 3.1.0. 

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/apps.py", line 24, in ready
    self.module.autodiscover()
  File "/usr/lib/python3.8/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/usr/lib/python3.8/site-packages/django/utils/module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/www/html/sopds/constance/admin.py", line 20, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/lib/python3.8/site-packages/django/utils/__init__.py)

**Comment by HalfWorm** [comment]
Я думал SOPDS работает на django  ниже 2.2
Ну если верить содержащийся в 'requirements.txt' 
'Django>=1.10,<2.2; python_version >= '3.4''

**Comment by walkman99** [comment]
Похожая ошибка при import name 'ugettext_lazy', но 'ugettext_lazy'  was deprecated in v2.2 and no longer used in django v3+.
В requirements.txt:
Django>=1.10 ; python_version >= '3.4'

После установки Django 2.1 вылезла другая ошибка: 
_TypeError: translation() got an unexpected keyword argument 'codeset'_

Не понимаю, какую версию нужно установить.
